openapi: 3.0.0
info:
  version: 0.1.0
  title: DLC Link Prototype Wallet API
  description: Wallet API that connects to Oracle
servers:
  - url: http://localhost:8085
externalDocs:
  description: Find out more about DLC.Link
  url: https://dlc.link
tags:
  - name: contract
    description: Smart contract operations for the wallet
    externalDocs:
      description: Find out more about DLC.Link
      url: https://dlc.link

paths:
  /cleanup:
    delete:
      tags:
        - contract
      description: Delete all contracts (enabled for dev envs)
      responses:
        '204':
          description: Deletion successful response (no content)
  /offer:
    post:
      tags:
        - contract
      description: Get an offer message for an enumerated event
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/OfferRequest'
      responses:
        '201':
          description: Successful response (Accepted)
  /offer/accept:
    put:
      tags:
        - contract
      description: Process an accept message (accept offer)
      requestBody:
        content:
          application/json:
            schema:
              type: object
              required:
                - acceptMessage
              properties:
                acceptMessage:
                  type: string
      responses:
        '201':
          description: Successful response (Accepted)
components:
  schemas:
    OfferRequest:
      type: object
      required:
        - uuid
        - acceptCollateral
        - offerColateral
        - totalOutcomes
      properties:
        uuid:
          type: string
          description: Unique event id
        acceptCollateral:
          type: number
          description: The collateral of the accepting party
        offerCollateral:
          type: number
          description: The collateral of the offering party
        totalOutcomes:
          type: number
          description: Total outcomes for the payout
